import styles from './layout.module.scss';
import Head from 'next/head';
import Nav from './Nav';
import React from 'react';

export default function Layout(props) {
	return (
		<div className={styles.layout}>
				<title>Crown Clothing || Choose You Love</title>
				<Head>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Nav />
				<main className={styles.main}>{props.children}</main>
		</div>
	);
}
